export const NICE_CLASSES = [
  { id: 1, label: "Classe 1", description: "Produits chimiques à usage industriel, scientifique, photographique" },
  { id: 2, label: "Classe 2", description: "Peintures, vernis, laques, colorants" },
  { id: 3, label: "Classe 3", description: "Cosmétiques, parfums, produits de toilette" },
  { id: 4, label: "Classe 4", description: "Huiles et graisses industrielles, lubrifiants, combustibles" },
  { id: 5, label: "Classe 5", description: "Produits pharmaceutiques et vétérinaires" },
  { id: 6, label: "Classe 6", description: "Métaux communs et leurs alliages, matériaux de construction métalliques" },
  { id: 7, label: "Classe 7", description: "Machines, machines-outils, moteurs" },
  { id: 8, label: "Classe 8", description: "Outils et instruments à main entraînés manuellement" },
  { id: 9, label: "Classe 9", description: "Appareils scientifiques, informatiques, électroniques" },
  { id: 10, label: "Classe 10", description: "Appareils et instruments chirurgicaux et médicaux" },
  { id: 11, label: "Classe 11", description: "Appareils d'éclairage, de chauffage, de réfrigération" },
  { id: 12, label: "Classe 12", description: "Véhicules, appareils de locomotion par terre, air ou eau" },
  { id: 13, label: "Classe 13", description: "Armes à feu, munitions et projectiles, explosifs" },
  { id: 14, label: "Classe 14", description: "Métaux précieux, joaillerie, horlogerie" },
  { id: 15, label: "Classe 15", description: "Instruments de musique" },
  { id: 16, label: "Classe 16", description: "Papier, articles de bureau, imprimés" },
  { id: 17, label: "Classe 17", description: "Caoutchouc, matières plastiques semi-ouvrées" },
  { id: 18, label: "Classe 18", description: "Cuir, bagages, sacs à main, parapluies" },
  { id: 19, label: "Classe 19", description: "Matériaux de construction non métalliques" },
  { id: 20, label: "Classe 20", description: "Meubles, miroirs, cadres" },
  { id: 21, label: "Classe 21", description: "Ustensiles de ménage, verrerie, porcelaine" },
  { id: 22, label: "Classe 22", description: "Cordes, ficelles, tentes, bâches" },
  { id: 23, label: "Classe 23", description: "Fils à usage textile" },
  { id: 24, label: "Classe 24", description: "Tissus, couvertures, linge de maison" },
  { id: 25, label: "Classe 25", description: "Vêtements, chaussures, chapellerie" },
  { id: 26, label: "Classe 26", description: "Dentelles, broderies, rubans, boutons" },
  { id: 27, label: "Classe 27", description: "Tapis, paillassons, revêtements de sols" },
  { id: 28, label: "Classe 28", description: "Jeux, jouets, articles de sport" },
  { id: 29, label: "Classe 29", description: "Viande, poisson, fruits et légumes conservés" },
  { id: 30, label: "Classe 30", description: "Café, thé, cacao, sucre, pâtisserie" },
  { id: 31, label: "Classe 31", description: "Produits agricoles, graines, fruits et légumes frais" },
  { id: 32, label: "Classe 32", description: "Bières, eaux minérales, boissons sans alcool" },
  { id: 33, label: "Classe 33", description: "Boissons alcoolisées (sauf bières)" },
  { id: 34, label: "Classe 34", description: "Tabac, articles pour fumeurs, allumettes" },
  { id: 35, label: "Classe 35", description: "Publicité, gestion des affaires commerciales" },
  { id: 36, label: "Classe 36", description: "Assurances, affaires financières et immobilières" },
  { id: 37, label: "Classe 37", description: "Construction, réparation, installation" },
  { id: 38, label: "Classe 38", description: "Télécommunications" },
  { id: 39, label: "Classe 39", description: "Transport, emballage, entreposage" },
  { id: 40, label: "Classe 40", description: "Traitement de matériaux" },
  { id: 41, label: "Classe 41", description: "Éducation, formation, divertissement, activités sportives" },
  { id: 42, label: "Classe 42", description: "Services scientifiques, technologiques, conception informatique" },
  { id: 43, label: "Classe 43", description: "Restauration, hébergement temporaire" },
  { id: 44, label: "Classe 44", description: "Services médicaux, vétérinaires, soins d'hygiène" },
  { id: 45, label: "Classe 45", description: "Services juridiques, sécurité, services personnels" },
];

export const TERRITORIES = [
  { id: "france", label: "France" },
  { id: "eu", label: "Union Européenne" },
  { id: "usa", label: "États-Unis" },
  { id: "international", label: "International" },
];
